# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 19:02
from __future__ import unicode_literals

import autoslug.fields
import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('type', models.CharField(choices=[('INT', 'Integer'), ('FLOAT', 'Float'), ('STRING', 'String'), ('DATE', 'Date'), ('DATETIME', 'Date & time')], default='STRING', max_length=15)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('color', colorful.fields.RGBColorField(default='#87BBFF')),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('int_value', models.IntegerField(null=True)),
                ('float_value', models.FloatField(null=True)),
                ('string_value', models.CharField(max_length=256, null=True)),
                ('date_value', models.DateField(null=True)),
                ('datetime_value', models.DateTimeField(null=True)),
                ('datum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Datum')),
            ],
        ),
    ]
