# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_auto_20170217_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='date_value',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='datetime_value',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='float_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='int_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='string_value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
