# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-04 22:01
from __future__ import unicode_literals

import datetime

from django.db import migrations

from logger.models import Datum, Value


# this is absolutely filthy, may god have mercy on my soul
def increment_hour_by_one(apps, schema_editor):
    work = Datum.objects.filter(slug="work")
    values = Value.objects.filter(datum=work)

    for value in values:
        value.timestamp += datetime.timedelta(hours=1)
        value.save()


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_auto_20170223_2122'),
    ]

    operations = [
        migrations.RunPython(increment_hour_by_one)
    ]
